### ISSUE TITLE
set charging power for all placed logistic stations

### ISSUE THREAD

**Issue by h3fang** [Pasukaru/DSP-Mods#5]
The recent game update reset all the logistic stations power charge rate to the default. Link <https://www.reddit.com/r/Dyson_Sphere_Program/comments/lyh32p/update_reset_logistics_stations_max_power/>

Is it possible to set the power charge rate to max for all placed logistic stations? If not, for all logistic stations on current planet? Or modify the save file directly?

Thanks!

**Comment by Pasukaru** [comment]
It's not really in the scope of this mod. I haven't looked into the already placed structures, but I would guess it's possible to find all of them and set the power to max. Not sure if you would need to be on the planet, or if it could work for all planets.

I also never took a look at the save game yet, It's stored in there, because when you reload a save, it gets the correct power again, but I don't know the save game structure or even it's format.

**Comment by Pasukaru** [comment]
New mod: https://dsp.thunderstore.io/package/Pasukaru/FixStationConfig/1.0.0/

**Comment by h3fang** [comment]
Thank you very much!
But a little bit too late. I just manually fixed them all. T_T
